---
# filebeat

- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Get filebeat 8.6.2
  ansible.builtin.get_url:  
    url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.6.2-amd64.deb
    dest: /home/user/

- name: Install filebeat
  apt:
    deb: /home/user/filebeat-8.6.2-amd64.deb 

- name: Copy config file for filebeat
  template:
    src: ../templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0600
    owner: root
    group: root


- name: Systemctl daemon reload
  systemd:
    daemon_reload: true
    name: filebeat.service
    state: started

- name: restarted nginx    
  service:
    name: nginx
    state: restarted

- name: Systemctl enable  filebeat
  systemd:
    name: filebeat.service
    state: restarted