- name: Play elasticsearch
  hosts: elasticsearch
  become: yes
  tasks:

    - name: Install reqs for Docker
      apt: 
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest 
        update_cache: yes


    - name: Install the Docker module for Python
      pip:
        name: docker
    
    - name: Create a directory /etc/elasticsearch/data if it does not exist
      ansible.builtin.file:
        path: /etc/elasticsearch/data
        state: directory
        mode: '0775'

    - name: Create container elasticsearch
      docker_container:
        name: "elasticsearch"
        image: "elasticsearch:8.8.0"
        volumes:
          - "/etc/elasticsearch/data:/usr/share/elasticsearch/data"
        # ports:
        #   - "9200:9200"
        #   - "9300:9300"
        env:
          ELASTICSEARCH_CLUSTER_NAME=makhota-diplom
          xpack.security.enrollment.enabled=true
          #discovery.type=single-node
          #ELASTIC_PASSWORD=123
          #xpack.license.self_generated.type=basic
          path.data=/usr/share/elasticsearch/data
          #bootstrap.memory_lock=true
          #ES_JAVA_OPTS=-Xms1g -Xmx1g
        state: started
        restart_policy: always
        network_mode: host
