- name: Play kibana
  hosts: kibana
  become: yes
  tasks:

    - name: Install reqs for Docker
      apt: 
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest 
        update_cache: yes


    - name: Install the Docker module for Python
      pip:
        name: docker
    
    - name: Create container
      docker_container:
        name: "Kibana"
        image: "kibana:8.8.0"
        ports:
        - "5601:5601"
        env:
            ELASTICSEARCH_HOSTS='["https://10.3.0.100:9200"]'
          #  elasticsearch.username=elasticsearch
          #  elasticsearch.password=123
        state: started
        restart_policy: always
        network_mode: host
