- name: Play nginx-exporter
  hosts: web
  become: yes
  tasks:

    
  - name: download nginx log exporter
    get_url:
      url: https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.9.2/prometheus-nginxlog-exporter_1.9.2_linux_amd64.tar.gz
      dest: /tmp
      
  - name: unarchive nginx log exporter
    unarchive:
      remote_src: yes
      src: /tmp/prometheus-nginxlog-exporter_1.9.2_linux_amd64.tar.gz
      dest: /tmp
      
  - name: move nginx log exporter to /usr/bin
    copy:
      remote_src: yes
      src: /tmp/prometheus-nginxlog-exporter
      dest: /usr/bin/prometheus-nginxlog-exporter
      owner: root
      group: root
      mode: 0777
      
  - name: copy  nginx log exporter config
    copy:
      src: ./files_nginx-exporter/prometheus-nginxlog-exporter.hcl
      dest: /etc/prometheus-nginxlog-exporter.hcl
      
  - name: install unit file to systemd
    copy:
      src: ./files_nginx-exporter/nginxlog-exporter.service
      dest: /etc/systemd/system/prometheus-nginxlog-exporter.service
      owner: root
      group: root
      mode: 0600

  
  - name: nginxlog-exporter started
    systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: prometheus-nginxlog-exporter.service