- name: Play node-exporter
  hosts: web
  become: yes
  tasks:

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/user/node-exporter
        state: directory
        mode: '0777'

    - name: Copy dir
      ansible.builtin.copy:
        src: /home/user/ansible/files_node_exporter/
        dest: /home/user/node-exporter/
        mode: '0777'

    - name: Install node-exporter
      ansible.builtin.shell: chmod +x /home/user/node-exporter/node_exporter.sh && sudo /home/user/node-exporter/node_exporter.sh
      register: result

    - name: Print stdout
      debug:
        var: result.stdout